service: wise-bot

provider:
  name: aws
  runtime: nodejs8.10
  profile: personal
  region: eu-west-1
  stage: dev

functions:
  mineQuotes:
    handler: src/index.main
    events:
      - http:
          path: webhook
          method: get
          cors: true