service: wise-bot

provider:
  name: aws
  runtime: nodejs8.10
  profile: personal
  region: eu-west-1
  stage: dev
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  test:
    handler: src/index.main
    events:
      - http:
          path: webhook
          method: get
          cors: true
  mine:
    handler: src/index.mine
    events:
      - http:
          path: webhook
          method: get
          cors: true